data:
  ag_news: "wangrongsheng/ag_news"

input:
  max_seq_length: 128
  num_classes: 4

finetune:
  name: "bert-base-uncased"
  batch_size: 16
  learning_rate: 0.00002
  epochs: 3
  save_model_path: "model/"

training:
  early_stopping: True
  patience: 3
  use_gpu: True
  gpu_device: 0

rl_training:
  episode: 5000

logging:
  log_dir: "log/"
  log_level: "INFO"

other:
  seed: 42
