data:
  ag_news: "wangrongsheng/ag_news"

input:
  max_seq_length: 128
  num_classes: 4

finetune:
  name: "bert-base-uncased"
  batch_size: 16
  learning_rate: 0.00002
  epochs: 3
  save_model_path: "model/"

training:
  early_stopping: True
  patience: 3
  use_gpu: True
  gpu_device: 0

rl_training:
  episode: 5000
  learning_rate: 0.000005
  action_read: 0
  action_predict: 1
  penalty_read: -0.01
  penalty_predict_at_the_end: -0.5
  penalty_predict: -1
  reward_predict: 1
  reward_predict_at_the_end: 0.5

logging:
  log_dir: "log/"
  log_level: "INFO"

other:
  seed: 42
